name: messenger_like_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  provider: ^6.1.5+1
  supabase_flutter: ^2.12.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.5.4
  internet_connection_checker_plus: ^2.9.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
